<a href="https://colab.research.google.com/github/saksham1965/data-analyst/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving raw_data_unmodified.csv to raw_data_unmodified.csv

In [5]:
import pandas as pd

df = pd.read_csv('/content/raw_data_unmodified.csv')
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [7]:
df = df.replace(['?', 'N/A', 'na', ''], np.nan)
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     3
director_facebook_likes      2
actor_3_facebook_likes       0
actor_1_facebook_likes       0
gross                        0
num_voted_users              1
cast_total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
actor_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [10]:
print(df.isnull().sum())

print(df.isnull().mean() * 100)

movie_title                  0
num_critic_for_reviews       0
duration                     3
director_facebook_likes      2
actor_3_facebook_likes       0
actor_1_facebook_likes       0
gross                        0
num_voted_users              1
cast_total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
actor_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64
movie_title                   0.000000
num_critic_for_reviews        0.000000
duration                     21.428571
director_facebook_likes      14.285714
actor_3_facebook_likes        0.000000
actor_1_facebook_likes        0.000000
gross                         0.000000
num_voted_users               7.142857
cast_total_facebook_likes    14.285714
facenumber_in_poster         35.714286
num_user_for_reviews          0.000000
budget                        0.000000
title_year                    0.000000
actor_2_facebook_likes        7.142857
imdb_score                    0.000000
title_year.1                 50.000000
dtype: float64

In [11]:
df.dtypes

movie_title                   object
num_critic_for_reviews         int64
duration                     float64
director_facebook_likes       object
actor_3_facebook_likes         int64
actor_1_facebook_likes         int64
gross                          int64
num_voted_users              float64
cast_total_facebook_likes    float64
facenumber_in_poster         float64
num_user_for_reviews           int64
budget                         int64
title_year                     int64
actor_2_facebook_likes       float64
imdb_score                   float64
title_year.1                 float64
dtype: object

In [12]:
df[df.duplicated()]

Empty DataFrame
Columns: [movie_title, num_critic_for_reviews, duration, director_facebook_likes, actor_3_facebook_likes, actor_1_facebook_likes, gross, num_voted_users, cast_total_facebook_likes, facenumber_in_poster, num_user_for_reviews, budget, title_year, actor_2_facebook_likes, imdb_score, title_year.1]
Index: []